### ISSUE TITLE
Warning: Component HamburgerMenu declared `PropTypes` instead of `propTypes`

### ISSUE THREAD

**Issue by axhamre** [cameronbourke/react-hamburger-menu#12]
Thanks for a great package. I'm getting the following warning:

![screenshot 2018-04-17 00 08 08](https://user-images.githubusercontent.com/1907343/38837829-c556d44c-41d3-11e8-8f6a-c2e6ffa75867.png)

**Comment by cameronbourke** [comment]
Hey @hundsim thanks for the PR!

It is fixed in this release:
https://github.com/cameronbourke/react-hamburger-menu/releases/tag/v1.1.1

**Comment by Fi1osof** [comment]
@1.2.0 got it again.
console.log('[HamburgerMenu] props', props);
http://joxi.ru/a2XWaY6IDkV0em

And why here not actual version source?

**Comment by cameronbourke** [comment]
@Fi1osof Strange! So you are still seeing the `propTypes` warning?

Also, in regard to `console.log('[HamburgerMenu] props', props);`. That was an oversight from me, the deployment pipeline must not of compiled again after removing the console.logs. I'll put a `patch` release today to address that!

**Comment by Fi1osof** [comment]
@cameronbourke yes, i still view logs in dev tools. And see them in sources here: https://npm.runkit.com/react-hamburger-menu (see Browse Files panel).

**Comment by cameronbourke** [comment]
@Fi1osof thanks for picking that up! I've now released `v1.2.1` which removes the logs.
