### ISSUE TITLE
Push latest fixes for React 15 to NPM

### ISSUE THREAD

**Issue by IonoclastBrigham** [cameronbourke/react-hamburger-menu#7]
Simply put, the version in the NPM repo doesn't have all the latest code fixes that are present on github.

**Comment by dciesielkiewicz** [comment]
Hello
You've done already a great job. It looks very good and works as it should.
I think your fixes would be really helpful. Eg. I have a warning with span marginTop being string '-1'. It's now fixed on GitHub. Could you push the changes into NPM?

**Comment by cameronbourke** [comment]
@IonoclastBrigham @dciesielkiewicz My apologies for being slack on this, it has only just come to my attention. Version 1.0.0 has been published to mirror master.
