### ISSUE TITLE
React ^15.5 PropTypes is deprecated 

### ISSUE THREAD

**Issue by warrenc5** [cameronbourke/react-hamburger-menu#8]
Hello, I upgraded to react 16 and PropTypes is deprecated.  So I added.. to dist/index.js
var PropTypes = require('prop-types');

HamburgerMenu.PropTypes = {
	isOpen: PropTypes.bool.isRequired,
	menuClicked: PropTypes.func.isRequired,
	width: PropTypes.number,
	height: PropTypes.number,
	strokeWidth: PropTypes.number,
	rotate: PropTypes.number,
	color: PropTypes.string,
	borderRadius: PropTypes.number,
	animationDuration: PropTypes.number
};

**Comment by cameronbourke** [comment]
@warrenc5 Thanks for the PR, I'm so sorry that it took me this long to get back to you, I only released this issue was here this morning!

**Comment by cameronbourke** [comment]
Closed now that [v1.1.0](https://github.com/cameronbourke/react-hamburger-menu/releases/tag/v1.1.0) is released
